import React, { useEffect, createRef } from 'react'
import { Link, graphql } from 'gatsby'
import Img from 'gatsby-image'

// Custom Scene
// import BaseThreeScene from '../components/three/BaseThreeScene'
import MultiThreeScene from '../components/three/MultiThreeScene'
// import GradientScene from '../components/three/GradientScene'
// import PlaneLayerScene from '../components/three/PlaneLayerScene'
import PeriodicTableScene from '../components/three/PeriodicTableScene'
import PointDynamicScene from '../components/three/PointDynamicScene2'
import ObjLoaderScene from '../components/three/ObjLoaderScene'
import GLSLScene from '../components/three/GLSLScene'
import BufferLineScene from '../components/three/BufferLineScene'
import ZoomScene from '../components/three/ZoomScene'
import BoxAnimationScene from '../components/three/BoxAnimationScene'
import BlockchainAnimationScene from '../components/three/BlockchainAnimationScene'
import MLAnimationScene from '../components/three/MLAnimationScene'
import TownScene from '../components/three/TownScene'
import PointLightScene from '../components/three/PointLightScene'
import TessellationScene from '../components/three/TessellationScene'
import AttributeLineScene from '../components/three/AttributeLineScene'
import EffectsAnaglyphScene from '../components/three/EffectsAnaglyphScene'
import WebGLShaderScene from '../components/three/WebGLShaderScene'
import WebGLLineScene from '../components/three/WebGLLineScene'
import InstancingScatterScene from '../components/three/InstancingScatterScene'
import OceanScene from '../components/three/OceanScene'
import GeometryHierarchyScene from '../components/three/GeometryHierarchyScene'
import DrawRangeScene from '../components/three/DrawRangeScene'
import CrossfadeScene from '../components/three/CrossfadeScene'
import AttributePoint2Scene from '../components/three/AttributePoint2Scene'
import CSS3DSpriteScene from '../components/three/CSS3DSpriteScene'
import RollercoasterScene from '../components/three/RollercoasterScene'
import AnimationGroupsScene from '../components/three/AnimationGroupsScene'
import SkinningMorphScene from '../components/three/SkinningMorphScene'
import GpgpuBirdsScene from '../components/three/GpgpuBirdsScene'
import AttributePointScene from '../components/three/AttributePointScene'
import AnimationClothScene from '../components/three/AnimationClothScene'
import ClippingAdvancedScene from '../components/three/ClippingAdvancedScene'
import PointWaveScene from '../components/three/PointWaveScene'
import MiscLookAtScene from '../components/three/MiscLookAtScene'
import InteractiveCubesScene from '../components/three/InteractiveCubesScene'
import DiskFieldAnimation from '../components/three/original/DiskFeild'
import InteractivePointScene from '../components/three/InteractivePointScene'
import TestMemoryScene from '../components/three/TestMemoryScene'
import YouTubeScene from '../components/three/YoutubeScene'
import PostprocessingAdvancedScene from '../components/three/PostprocessingAdvancedScene'
import AfterImageScene from '../components/three/AfterImageScene'
import PostprocessingGlitchSceme from '../components/three/PostprocessingGlitchSceme'
import AnimationRubiksCubeScene from '../components/three/AnimationRubiksCubeScene'
import EffectsAsciiScene from '../components/three/EffectsAsciiScene'
import CubemapScene from '../components/three/CubemapScene'
import PhysicalTransparencyScene from '../components/three/PhysicalTransparencyScene'
import SpotlightsScene from '../components/three/SpotlightsScene'
import PointlightsScene from '../components/three/PointlightsScene'
import KinectScene from '../components/three/KinectScene'
import LavaScene from '../components/three/LavaScene'
import BuffergeometryInstancingScene from '../components/three/BuffergeometryInstancingScene'

export default () => (
  <>
    <BuffergeometryInstancingScene />
  </>
)
